### ISSUE TITLE
Do not work with MPT!

### ISSUE THREAD

**Issue by AreChen** [Amands2Mello/AmandsSense#4]
Hope to be compatible with MPT, very grateful, excellent plugin!

**Comment by WAR282737** [comment]
MPT not working +

**Comment by DENTiller** [comment]
Please, mod not working with MPT or Fika mod.

**Comment by Amands2Mello** [comment]
I can't test MPT/Fika, but I applied the same fix from the graphics mod which worked for some people so might be working

**Comment by OmGxM** [comment]
Yeah, Just downloaded now and still seems to not work with Fika

**Comment by WalnutUK** [comment]
Hi, Amand, Thanks for your work on these mods, Great additions to the game. Can confirm what OmGxM Said earlier, It appears the fix that was applied doesnt work with MPT/Fika. tested with the pre-release 2.0.0 Is there any output from the server/game that i can enable to help you identify and test this compatibility? Happy to help.

**Comment by Amands2Mello** [comment]
sorry I was meant to release the update but had other issues, I'll be putting the build for it now

**Comment by WalnutUK** [comment]
Legend, Thank you.

**Comment by WalnutUK** [comment]
Just checked out the latest build you've popped up. Confirmed working for me with FIKA.  Thank you.

**Comment by OmGxM** [comment]
Ooooooh nice, thanks Amands, I’ll be sure to update the mod tomorrow appreciate the quickness your a god.

**Comment by AreChen** [comment]
thanks!
